version: '3'

services:
  app:
    build: .
    container_name: adonis_app
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3333:3333'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: adonis_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adonis_db
      MYSQL_USER: adonis
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: adonis_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  mysql_data:
